import { services } from '@misiki/litekart-utils'

export const {
	AddressService,
	AutocompleteService,
	BannersService,
	BlogService,
	BrandService,
	CartService,
	CategoryService,
	ChatService,
	CollectionService,
	ContactService,
	CountryService,
	CouponService,
	DealsService,
	DemoRequestService,
	DiscountService,
	FaqService,
	FeedbackService,
	GalleryService,
	HokodoService,
	HomeService,
	InitService,
	InvoiceService,
	MenuService,
	OrdersService,
	PageService,
	PaymentMethodService,
	PopularityService,
	PopularSearchService,
	ProductService,
	ReelService,
	ReturnService,
	ReviewService,
	StoreService,
	UserService,
	VendorService,
	WishlistService,
	ZipService
} = services

export * as VarniProductService from './varni/product-service'
